import React from 'react';
import { Wand2, Gauge, Search, MousePointerClick, Share2, EyeOff } from 'lucide-react';

/**
 * Schema Explorer spotlight: plays the product demo and describes the advantages
 * of the ER map our agents generate automatically. Anchored at #schema-explorer.
 */

const benefits = [
  {
    icon: <Wand2 className="w-5 h-5" />,
    title: 'Generated by our agents',
    body: 'No manual modelling. Our agents crawl your schema and build the full entity-relationship map for you, in minutes.',
  },
  {
    icon: <Gauge className="w-5 h-5" />,
    title: 'Fluid at any scale',
    body: 'Hundreds of tables stay smooth to pan and zoom. Only what is on screen is rendered, so it never lags.',
  },
  {
    icon: <Search className="w-5 h-5" />,
    title: 'Search and focus',
    body: 'Find any table instantly. It lights up with its direct relations while the rest dims, and the view recenters on it.',
  },
  {
    icon: <MousePointerClick className="w-5 h-5" />,
    title: 'Click to inspect',
    body: 'Open any table to see its columns, primary and foreign keys, and an instant row-count estimate.',
  },
  {
    icon: <Share2 className="w-5 h-5" />,
    title: 'Relationships at a glance',
    body: 'Cardinality is read for you: one-to-many links are marked, and junction tables surface many-to-many relations.',
  },
  {
    icon: <EyeOff className="w-5 h-5" />,
    title: 'Noise-free by default',
    body: 'Audit, log and system tables are detected and hidden, so you see the business model, not the plumbing.',
  },
];

const SchemaExplorerSection: React.FC = () => {
  return (
    <section id="schema-explorer" className="py-20 relative overflow-hidden scroll-mt-20" style={{ background: 'linear-gradient(180deg,#0a0a0f 0%,#140a2e 55%,#0a0a0f 100%)' }}>
      {/* Ambient orbs */}
      <div className="absolute -top-24 left-1/4 w-[500px] h-[500px] rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle,rgba(139,92,246,0.22),transparent 65%)', filter: 'blur(70px)' }} />
      <div className="absolute bottom-0 right-1/5 w-[400px] h-[400px] rounded-full pointer-events-none" style={{ background: 'radial-gradient(circle,rgba(124,58,237,0.18),transparent 65%)', filter: 'blur(70px)' }} />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center mb-14">
          <span className="inline-block px-4 py-1.5 rounded-full text-sm font-semibold mb-5 text-violet-200 border border-violet-400/25" style={{ background: 'rgba(139,92,246,0.12)' }}>
            Schema explorer
          </span>
          <h2 className="text-4xl sm:text-5xl font-black text-white mb-5 leading-tight">
            Your database,{' '}
            <span style={{ background: 'linear-gradient(90deg,#c4b5fd,#a78bfa 50%,#7c3aed)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
              mapped by AI
            </span>
          </h2>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">
            Our agents turn your live schema into an interactive map you can search, focus and inspect, however many tables it holds.
          </p>
        </div>

        {/* Video in a browser-style frame */}
        <div className="max-w-4xl mx-auto mb-16">
          <div className="rounded-2xl overflow-hidden border border-violet-400/20 shadow-2xl" style={{ boxShadow: '0 30px 80px rgba(124,58,237,0.35)' }}>
            <div className="flex items-center gap-1.5 px-4 py-2.5 bg-white/5 border-b border-white/10">
              <span className="w-3 h-3 rounded-full bg-white/20" />
              <span className="w-3 h-3 rounded-full bg-white/20" />
              <span className="w-3 h-3 rounded-full bg-white/20" />
              <span className="ml-3 text-[11px] text-gray-400 font-medium">Database schema</span>
            </div>
            <video
              src="/flexiDbExplore.mp4"
              autoPlay
              muted
              loop
              playsInline
              className="w-full block bg-black"
            />
          </div>
        </div>

        {/* Benefits */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {benefits.map((b) => (
            <div key={b.title} className="rounded-2xl p-6 border border-white/10 bg-white/5 backdrop-blur-sm hover:bg-white/10 transition-colors">
              <div className="w-10 h-10 rounded-lg flex items-center justify-center mb-3 text-white" style={{ background: 'linear-gradient(135deg,#8b5cf6,#6d28d9)' }}>
                {b.icon}
              </div>
              <h3 className="text-base font-bold text-white mb-1.5">{b.title}</h3>
              <p className="text-sm text-gray-300 leading-relaxed">{b.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default SchemaExplorerSection;
