"""add kg_built column to connector_syncs

Revision ID: 7a2a73ad61b1
Revises: b7d574f4a085
Create Date: 2026-06-25 03:30:18.961062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2a73ad61b1'
down_revision = 'b7d574f4a085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector_syncs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kg_built', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector_syncs', schema=None) as batch_op:
        batch_op.drop_column('kg_built')

    # ### end Alembic commands ###
