"""add ressource_chunks ingestion_status and versioning

Revision ID: 9139bf022744
Revises: 915624d13a9b
Create Date: 2026-06-23 02:34:35.221641

"""
import os
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '9139bf022744'
down_revision = '915624d13a9b'
branch_labels = None
depends_on = None


def upgrade():
    # The VECTOR column below needs pgvector, and a fresh database (Render, CI)
    # ships without it. Idempotent, so re-running on a DB that already has it
    # is a no-op.
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(), nullable=True),
    sa.Column('embedding', Vector(int(os.getenv('EMBEDDING_DIMENSIONS', '1536'))), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('external_modified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('external_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('ingestion_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ingestion_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ingested_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('ingested_at')
        batch_op.drop_column('ingestion_error')
        batch_op.drop_column('ingestion_status')
        batch_op.drop_column('file_size_bytes')
        batch_op.drop_column('external_version')
        batch_op.drop_column('external_modified_at')
        batch_op.drop_column('content_hash')

    op.drop_table('resource_chunks')
    # ### end Alembic commands ###
