"""add leads table

Revision ID: 915624d13a9b
Revises: 1a8f3acae2cf
Create Date: 2026-06-17 04:20:22.700424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915624d13a9b'
down_revision = '1a8f3acae2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('work_email', sa.String(), nullable=False),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
