"""add knowledge graph

Revision ID: b7d574f4a085
Revises: a3f1c8d20e55
Create Date: 2026-06-24 13:59:54.341970

"""
import os
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'b7d574f4a085'
down_revision = 'a3f1c8d20e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('connector_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kgnode_metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', Vector(int(os.getenv('EMBEDDING_DIMENSIONS', '1536'))), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kg_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('kgedge_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['kg_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['kg_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector_syncs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_syncs_connector_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connector_syncs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_syncs_connector_id'), ['connector_id'], unique=False)

    op.drop_table('kg_edges')
    op.drop_table('kg_nodes')
    # ### end Alembic commands ###
