"""add kg_processed_at to resource_chunks

Revision ID: f3a9c2b41d7e
Revises: 7a2a73ad61b1
Create Date: 2026-06-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a9c2b41d7e'
down_revision = '7a2a73ad61b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kg_processed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_resource_chunks_kg_processed_at'),
            ['kg_processed_at'],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_chunks_kg_processed_at'))
        batch_op.drop_column('kg_processed_at')

    # ### end Alembic commands ###
